### ISSUE TITLE
Introducing a new paper on role-playing LLM agents (ACL 2024 Findings)

### ISSUE THREAD

**Issue by ahnjaewoo** [nuochenpku/Awesome-Pesonalized-Papers#1]
Hi, nice to see a fantastic resource for role-playing agents!

I wanted to highlight a recent paper presented at ACL 2024 Findings: [TimeChara: Evaluating Point-in-Time Character Hallucination of Role-Playing Large Language Models](https://ahnjaewoo.github.io/timechara).
This study focuses on assessing hallucinations in role-playing LLM agents when they simulate characters at specific moments in time.

We would greatly appreciate it if you could consider adding our paper to your survey.
Thanks!

**Comment by nuochenpku** [comment]
Sure, In fact, I have noticed this paper during acl review. But it seems this paper is just released recently.

**Comment by ahnjaewoo** [comment]
Thank you for adding our paper and for your valuable comments as an ACL reviewer!!
