### ISSUE TITLE
Request to Update Citation for 'PRODIGy: A PROfile-based DIalogue Generation Dataset' Paper

### ISSUE THREAD

**Issue by danie08** [nuochenpku/Awesome-Pesonalized-Papers#3]
Thank you for your work in creating and maintaining this repository!

I am reaching out to request an update to the citation of the paper "PRODIGy: a PROfile-based DIalogue Generation dataset." The paper has been accepted at NAACL 2024 and can now be cited using the following link: https://aclanthology.org/2024.findings-naacl.222/.

We would greatly appreciate it if you could consider updating the citation.

Thank you very much for your time and effort!

**Comment by jerrynchen** [comment]
Sorry for the late response, we will cite your work and update our paper.
