### ISSUE TITLE
Request to Consider Adding “MMRole: A Comprehensive Framework for Developing and Evaluating Multimodal Role-Playing Agents” Paper

### ISSUE THREAD

**Issue by YanqiDai** [nuochenpku/Awesome-Pesonalized-Papers#4]
Thank you for your work in writing the survey paper and creating this repository!

I would like to suggest the addition of our recent work, [MMRole: A Comprehensive Framework for Developing and Evaluating Multimodal Role-Playing Agents](https://arxiv.org/abs/2408.04203), to this repository and your paper. Our work includes a personalized multimodal dataset and a robust evaluation method, which is highly relevant to the Multi-Modal Integration in RPLAs part in Sec. 7 of the survey paper.

We would greatly appreciate it if you could consider this addition.

**Comment by nuochenpku** [comment]
Sure, I will add your paper to our work, and update it next week.
